from enum import Enum
class CSOpCode(Enum):

   LOAD_MODULE = 1
   PUSH_INTEGER = 2
   PUSH_DOUBLE  = 3
   PUSH_STRING = 4
   PUSH_BOOLEAN = 5
   PUSH_NULL = 6
   PUSH_OBJECT = 7
   PUSH_CODE   = 8
   PUSH_NAME  = 9
   PUSH_LOCAL  = 10
   PUSH_CONST = 11
   MAKE_ARRAY = 12
   MAKE_OBJECT = 13
   MAKE_CLASS  = 14
   MAKE_FUNCTION  = 15
   MAKE_MODULE = 16
   GET_ATTRIB  = 17
   GET_METHOD  = 18
   SET_ATTRIB  = 19
   MAKE_VAR    = 20
   STORE_NAME  = 21
   MAKE_LOCAL  = 22
   STORE_LOCAL = 23
   CALL       = 24
   CALL_METHOD = 25
   UNARY_OP   = 26
   BINARY_POW = 27
   BINARY_MUL = 28
   BINARY_DIV = 29
   BINARY_MOD = 30
   BINARY_ADD = 31
   BINARY_SUB = 32
   BINARY_LSHIFT = 33
   BINARY_RSHIFT = 34
   BINARY_AND = 35
   BINARY_XOR = 36
   BINARY_OR  = 37
   BINARY_SUBSCRIPT = 38
   SET_SUBSCRIPT = 39
   COMPARE_OP = 40

   INPLACE_POW = 41
   INPLACE_MUL = 42
   INPLACE_DIV = 43
   INPLACE_MOD = 44
   INPLACE_ADD = 45
   INPLACE_SUB = 46
   INPLACE_LSHIFT = 47
   INPLACE_RSHIFT = 48
   INPLACE_AND = 49
   INPLACE_XOR = 50
   INPLACE_OR = 51

   POP_JUMP_IF_FALSE = 51
   POP_JUMP_IF_TRUE = 52
   JUMP_IF_FALSE_OR_POP = 53
   JUMP_IF_TRUE_OR_POP = 54
   JUMP_NOT_EQUAL = 55
   JUMP_EQUAL = 57
   JUMP_TO = 58
   ABSOLUTE_JUMP = 59

   SETUP_TRY = 60
   POP_TRY = 61

   THROW_ERROR   = 62
   PRINT_OBJECT = 63
   DUP_TOP = 64
   POP_TOP = 65
   NEW_BLOCK = 66
   END_BLOCK = 67
   NO_OPERATION = 68
   RETURN_OP = 69